export enum SubscriptionEvent {
  personLogged = 'personLogged',
  assetAdded = 'assetAdded',
  assetUpdated = 'assetUpdated',
  causeAdded = 'causeAdded',
  causeUpdated = 'causeUpdated',
  participantAdded = 'participantAdded',
  participantUpdated = 'participantUpdated',
  participantIdentityChanged = 'participantIdentityChanged',
  personAdded = 'personAdded',
  personUpdated = 'personUpdated',
  personPasswordUpdated = 'personPasswordUpdated',
  personProfileUpdated = 'personProfileUpdated',
  personCitizenCardUpserted = 'personCitizenCardUpserted',
  personAttributeAdded = 'personAttributeAdded',
  transactionAdded = 'transactionAdded',
  transactionUpdated = 'transactionUpdated',
}