version: '3.4'

networks:
  fabric:

services:
  solidarychain-server-graphql:
    image: solidarychain/solidarychain-server-graphql:1.0.1
    hostname: solidarychain-server-graphql
    domainname: solidarychain/solidarychain-server-graphql
    container_name: solidarychain-server-graphql
    restart: unless-stopped
    networks:
      - fabric
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/usr/src/app/packages/server-graphql/config
      # - ./network.env:/usr/src/app/packages/server-graphql/.env
      - ../crypto-config:/usr/src/app/packages/server-graphql/crypto-config
      - ./wallets/.hfc-org1:/usr/src/app/packages/server-graphql/.hfc-org1
      - ./org1.network-profile-raft.yaml:/usr/src/app/packages/server-graphql/org1.network-profile-raft.yaml
    ports:
      - 443:443
    env_file:
      - ./network.env
    extra_hosts:
      # was 
      # "orderer.example.com:192.168.1.61"
      - "orderer1.example.com:192.168.1.61"
      # added to try to fix raft error: [Channel.js]: Error: 14 UNAVAILABLE: TCP Read failed      
      # - "orderer2.example.com:192.168.1.62"
      # - "orderer3.example.com:192.168.1.63"
      # - "orderer4.example.com:192.168.1.64"
      # - "orderer5.example.com:192.168.1.65"
      # org1
      - "ca.org1.example.com:192.168.1.61"
      - "peer0.org1.example.com:192.168.1.61"
      - "peer1.org1.example.com:192.168.1.61"
      # org2
      - "ca.org2.example.com:192.168.1.62"
      - "peer0.org2.example.com:192.168.1.62"
      - "peer1.org2.example.com:192.168.1.62"
      # org3
      - "ca.org3.example.com:192.168.1.63"
      - "peer0.org3.example.com:192.168.1.63"
      - "peer1.org3.example.com:192.168.1.63"
      # org4
      - "ca.org4.example.com:192.168.1.64"
      - "peer0.org4.example.com:192.168.1.64"
      - "peer1.org4.example.com:192.168.1.64"
      # org5
      - "ca.org5.example.com:192.168.1.65"
      - "peer0.org5.example.com:192.168.1.65"
      - "peer1.org5.example.com:192.168.1.65"
